name: Beta Additions
main: ${main.class}
version: 1
description: >
  Additions for beta 1.3.
commands:
  heal:
    description: Heals yourself
    aliases: h
    usage: /heal
  nick:
    description: Nickname yourself
    aliases: nickname
    usage: /nick <nickname> [player]
  broadcast:
    description: Broadcast a message to the server
    aliases: bc
    usage: /broadcast <message>
  kill:
    description: Kill a player
    usage: /kill <player>
  list:
    description: List the players on the server
    aliases: l
    usage: /list
  coords:
    description: Show coords of player on the server
    aliases: coordinates
    usage: /coords <player>
  durability:
    description: Show the held tool's durability
    aliases: dur
    usage: /durability
  reloadconfigs:
    description: Reload configs
    aliases: reloadconfig
    usage: /reloadconfigs
